# .github/workflows/docker-build.yml
name: Build & Push Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hela repot
        uses: actions/checkout@v3

      - name: Logga in i registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Bygg och pusha Docker-image
        uses: docker/build-push-action@v3
        with:
          context: .                  # här pekar vi på repo-roten
          file: backend/Dockerfile    # Dockerfile i backend/
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/my-app:latest
            ${{ secrets.REGISTRY_URL }}/my-app:${{ github.sha }}
